version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: banco-postgres-tppe
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tppe_db
    ports:
      - "5432:5432"

